[package]
name = "kov-ray"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.5"
nom = "7.1.3"
nom_locate = "4.2.0"
rand = "0.8.5"
ray-tracer-rs = {git = "https://github.com/SNKK62/toy-ray-tracer-rs", rev = "191ce997fd432b7edae0509184fe972a59295423"}
pg-indicator = {git = "https://github.com/SNKK62/pg-indicator-rs", rev = "26e14d1f02f3fbca623ad617fc4d6dacb01a22aa"}

